version: "3.8"

services:

  web:
    stdin_open: true
    image: node:latest
    environment:
      - NODE_ENV=production
      - PATH=/app/node_modules/.bin:$PATH
    container_name: tenant-web
    working_dir: /app
    volumes:
      - ./web:/app
    command: ["npm", "start"]
    ports:
      - ${WEB_PORT}:3000
    networks:
      - tenant

  core:
    image: node:latest
    environment:
      - NODE_ENV=production
    container_name: tenant-core
    working_dir: /app
    volumes:
      - ./core:/app
    command: ["npm", "run", "start:dev"]
    restart: always
    depends_on:
      - mysql
    ports: 
      - ${CORE_PORT}:3000
    networks:
      - tenant

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    networks:
      - tenant
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      - mysql

  mysql:
    image: mysql:5.6
    container_name: tenant-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=tenant-db
      - MYSQL_USER=tenant
      - MYSQL_PASSWORD=tenant123
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - tenant

networks:
  tenant: