version: "3.8"

services:

  web:
    stdin_open: true
    image: node:latest
    environment:
      - NODE_ENV=production
      - PATH=/app/node_modules/.bin:$PATH
    container_name: tenant-web
    working_dir: /app
    volumes:
      - ./web:/app
    command: ["npm", "start"]
    ports:
      - ${WEB_PORT}:3000
    networks:
      - tenant

  core:
    image: safetyblanket/tenant:core
    container_name: tenant-core
    # volumes:
    #   - ./core:/app
    restart: always
    depends_on:
      - mysql
    ports: 
      - ${CORE_PORT}:3000
    networks:
      - tenant

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    networks:
      - tenant
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      - mysql

  mysql:
    image: safetyblanket/tenant:mysql
    container_name: tenant-mysql
    # volumes:
    #   - ./db/data:/var/lib/mysql
    #   - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - tenant

networks:
  tenant: